{{- if .Values.rancher.caBundlePEM }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rsm.fullname" . }}-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rsm.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: |
    {{- .Values.rancher.caBundlePEM | nindent 4 }}
{{- end }}
