linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: true

issues:
  exclude-rules:
    - path: zz_generated
      linters: [all]
