//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ManagedSecret) DeepCopyInto(out *ManagedSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ManagedSecret) DeepCopy() *ManagedSecret {
	if in == nil {
		return nil
	}
	out := new(ManagedSecret)
	in.DeepCopyInto(out)
	return out
}

func (in *ManagedSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ManagedSecretList) DeepCopyInto(out *ManagedSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ManagedSecretList) DeepCopy() *ManagedSecretList {
	if in == nil {
		return nil
	}
	out := new(ManagedSecretList)
	in.DeepCopyInto(out)
	return out
}

func (in *ManagedSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ManagedSecretSpec) DeepCopyInto(out *ManagedSecretSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]Target, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ManagedSecretSpec) DeepCopy() *ManagedSecretSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedSecretSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ManagedSecretStatus) DeepCopyInto(out *ManagedSecretStatus) {
	*out = *in
	if in.SyncStatus != nil {
		in, out := &in.SyncStatus, &out.SyncStatus
		*out = make([]ClusterSyncStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ManagedSecretStatus) DeepCopy() *ManagedSecretStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedSecretStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterSyncStatus) DeepCopyInto(out *ClusterSyncStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

func (in *ClusterSyncStatus) DeepCopy() *ClusterSyncStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterSyncStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
	if in.ClusterSelector != nil {
		in, out := &in.ClusterSelector, &out.ClusterSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}
